### ISSUE TITLE
Texts need adjustment

### ISSUE THREAD

**Issue by Ritwik880** [kartikcho/NoirNight#2]
The text Noir Night need adjustment and can solve by adding a slider to website

![Screenshot (324)](https://user-images.githubusercontent.com/54446880/102221991-da519500-3f08-11eb-8a3e-7640ba98422c.png)

**Comment by kartikcho** [comment]
Ah, thanks for reporting it! This is a known issue and we'll be rolling a new update with style fixes (and even some story ones too) soon.

**Comment by Lilykhan786** [comment]
working on it! :+1:
