### ISSUE TITLE
Add an 'incompatible browser' message for unsupported browsers

### ISSUE THREAD

**Issue by kartikcho** [kartikcho/NoirNight#3]

**Comment by Ritwik880** [comment]
Can I work on this?

**Comment by kartikcho** [comment]
Hey @Ritwik880 thanks for the offer but we intend to polish a lot of things before we release a `v1.0.0` of the app and make it open to contributions. 
Would love your help with newer issues after we hit that milestone internally!

**Comment by kartikcho** [comment]
Fixed in recent commits.
